logger: "info" # local, dev, prod

http_server:
  host: "127.0.0.1"
  port: "8080"
  timeout: 4s
  iddle_timout: 60s

db:
  rebuild_mode: true # Краждый запуск пересобирает базу данных
  mongo_db:
    uri: "mongodb://127.0.0.1:27017"